# Workflow to automate Terraform tasks
name: "Terraform"

# Trigger the workflow on a push event to the main branch
on:
  push:
    branches:
      - main

# Define environment variables for AWS access
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

# Define the job for Terraform
jobs:
  terraform:
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform: 1.1.9

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Check Terraform code formatting
        run: terraform fmt -check

      - name: Generate Terraform execution plan
        run: terraform plan
